import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, Validators } from '@angular/forms';
import { Usuario, Cheque, Beneficiario, Auditoria } from '../../models';
import { UsuarioService } from '../../services/usuario.service';
import { SessionService } from '../../services/session.service';
import { NotificationService } from '../../services/notification.service';
import { ChequeService } from '../../services/cheque.service';
import { BeneficiarioService } from '../../services/beneficiario.service';
import { AuditoriaService } from '../../services/auditoria.service';

@Component({selector:'app-login',standalone:false,template:`<div class="card-panel" style="max-width:420px;margin:4rem auto"><div class="card-title-group"><h2 class="card-title">Iniciar sesión</h2><p class="card-subtitle">Sistema Cheques</p></div><form [formGroup]="form" (ngSubmit)="entrar()"><div class="form-field"><label class="form-label">Usuario</label><input class="form-input" formControlName="usuario"></div><div class="form-field"><label class="form-label">Contraseña</label><input type="password" class="form-input" formControlName="password"></div><button class="btn btn-primary" style="width:100%;margin-top:1rem" [disabled]="form.invalid">Ingresar</button><p style="font-size:.8rem;color:var(--color-text-secondary);margin-top:1rem">Inicial: admin / admin</p></form></div>`})
export class LoginComponent { form;constructor(private fb:FormBuilder,private users:UsuarioService,private session:SessionService,private router:Router,private note:NotificationService){this.form=fb.group({usuario:['',Validators.required],password:['',Validators.required]});}async entrar(){const v=this.form.value;const u=await this.users.autenticar(v.usuario!,v.password!);if(!u){this.note.error('Usuario o contraseña incorrectos.');return;}this.session.iniciar(u);this.router.navigateByUrl('/dashboard');}}

@Component({selector:'app-detalle-cheque',standalone:false,template:`<div class="card-panel" *ngIf="cheque"><button class="btn btn-secondary" routerLink="/cheques">Volver</button><h2 class="card-title" style="margin-top:1rem">Cheque {{cheque.numeroCheque}}</h2><p><b>Beneficiario:</b> {{cheque.beneficiarioNombre}}</p><p><b>Tipo:</b> {{cheque.tipo}} · <b>Monto:</b> {{cheque.monto | number:'1.2-2'}} · <b>Estado:</b> {{cheque.estado}}</p><p><b>Concepto:</b> {{cheque.concepto}} · <b>Fecha:</b> {{cheque.fecha}}</p><p><b>Observaciones:</b> {{cheque.observaciones || '—'}}</p><app-historial [items]="historial"></app-historial></div>`})
export class DetalleChequeComponent implements OnInit { cheque:Cheque|null=null;historial:Auditoria[]=[];constructor(private route:ActivatedRoute,private service:ChequeService,private audit:AuditoriaService){}async ngOnInit(){const id=Number(this.route.snapshot.paramMap.get('id'));this.cheque=await this.service.getById(id);if(this.cheque){this.cheque=(await this.service.getAll()).find(x=>x.id===id)||this.cheque;this.historial=await this.audit.getByEntidad('Cheque',id);}}}
@Component({selector:'app-detalle-beneficiario',standalone:false,template:`<div class="card-panel" *ngIf="beneficiario"><button class="btn btn-secondary" routerLink="/beneficiarios">Volver</button><h2 class="card-title" style="margin-top:1rem">{{beneficiario.nombre}} {{beneficiario.apellido}}</h2><p><b>Documento:</b> {{beneficiario.tipoDocumento}} {{beneficiario.numeroDocumento}}</p><p><b>Banco:</b> {{beneficiario.banco}} · <b>Cuenta:</b> {{beneficiario.cuentaBancaria}}</p><p><b>Contacto:</b> {{beneficiario.telefono}} · {{beneficiario.correo}}</p><h3>Cheques asociados</h3><p *ngIf="!cheques.length">No tiene cheques asociados.</p><ul><li *ngFor="let c of cheques">{{c.numeroCheque}} — {{c.concepto}} — {{c.monto | number:'1.2-2'}}</li></ul><app-historial [items]="historial"></app-historial></div>`})
export class DetalleBeneficiarioComponent implements OnInit {beneficiario:Beneficiario|null=null;cheques:Cheque[]=[];historial:Auditoria[]=[];constructor(private route:ActivatedRoute,private service:BeneficiarioService,private cheque:ChequeService,private audit:AuditoriaService){}async ngOnInit(){const id=Number(this.route.snapshot.paramMap.get('id'));this.beneficiario=await this.service.getById(id);this.cheques=(await this.cheque.getAll()).filter(c=>c.beneficiarioId===id);this.historial=await this.audit.getByEntidad('Beneficiario',id);}}
@Component({selector:'app-historial',standalone:false,inputs:['items'],template:`<h3>Historial</h3><div *ngIf="!items?.length">Sin movimientos registrados.</div><ul><li *ngFor="let x of items">{{x.fecha | date:'short'}} — {{x.usuario}}: {{x.accion}} {{x.detalle}}</li></ul>`}) export class HistorialComponent {items:Auditoria[]=[];}
@Component({selector:'app-auditoria',standalone:false,template:`<div class="card-panel"><div class="card-title-group"><h2 class="card-title">Bitácora / Auditoría</h2></div><div class="controls-row"><select class="filter-select" [(ngModel)]="entidad" (change)="filtrar()"><option>Todos</option><option>Cheque</option><option>Beneficiario</option><option>Banco</option><option>Concepto</option><option>Usuario</option></select><input class="form-input" [(ngModel)]="usuario" (ngModelChange)="filtrar()" placeholder="Filtrar usuario"></div><div class="table-responsive"><table class="custom-table"><thead><tr><th>Fecha</th><th>Usuario</th><th>Entidad</th><th>Acción</th><th>Detalle</th></tr></thead><tbody><tr *ngFor="let x of filtrados"><td>{{x.fecha | date:'short'}}</td><td>{{x.usuario}}</td><td>{{x.entidad}}</td><td>{{x.accion}}</td><td>{{x.detalle}}</td></tr></tbody></table></div></div>`}) export class AuditoriaComponent implements OnInit {items:Auditoria[]=[];filtrados:Auditoria[]=[];entidad='Todos';usuario='';constructor(private audit:AuditoriaService){}async ngOnInit(){this.items=await this.audit.getAll();this.filtrar();}filtrar(){this.filtrados=this.items.filter(x=>(this.entidad==='Todos'||x.entidad===this.entidad)&&x.usuario.toLowerCase().includes(this.usuario.toLowerCase()));}}
@Component({selector:'app-reportes',standalone:false,template:`<div class="card-panel"><div class="card-title-group"><h2 class="card-title">Reportes</h2><p class="card-subtitle">Consulta y exportación de cheques</p></div><div class="controls-row"><input type="date" class="form-input" [(ngModel)]="desde"><input type="date" class="form-input" [(ngModel)]="hasta"><select class="filter-select" [(ngModel)]="estado"><option>Todos</option><option>Pendiente</option><option>Cobrado</option><option>Anulado</option></select><button class="btn btn-primary" (click)="filtrar()">Aplicar</button><button class="btn btn-secondary" (click)="csv()">Exportar CSV</button></div><p><b>Total:</b> {{total | number:'1.2-2'}} · Pendiente: {{porEstado('Pendiente') | number:'1.2-2'}} · Cobrado: {{porEstado('Cobrado') | number:'1.2-2'}}</p><div class="table-responsive"><table class="custom-table"><thead><tr><th>Número</th><th>Beneficiario</th><th>Concepto</th><th>Estado</th><th>Monto</th></tr></thead><tbody><tr *ngFor="let c of filtrados"><td>{{c.numeroCheque}}</td><td>{{c.beneficiarioNombre}}</td><td>{{c.concepto}}</td><td>{{c.estado}}</td><td>{{c.monto | number:'1.2-2'}}</td></tr></tbody></table></div></div>`}) export class ReportesComponent implements OnInit {items:Cheque[]=[];filtrados:Cheque[]=[];desde='';hasta='';estado='Todos';total=0;constructor(private cheques:ChequeService){}async ngOnInit(){this.items=await this.cheques.getAll();this.filtrar();}filtrar(){this.filtrados=this.items.filter(c=>(this.estado==='Todos'||c.estado===this.estado)&&(!this.desde||c.fecha.includes(this.desde))&&(!this.hasta||c.fecha.includes(this.hasta)));this.total=this.filtrados.reduce((s,c)=>s+c.monto,0);}porEstado(e:string){return this.filtrados.filter(c=>c.estado===e).reduce((s,c)=>s+c.monto,0);}csv(){const rows=['Número,Beneficiario,Concepto,Estado,Monto',...this.filtrados.map(c=>[c.numeroCheque,c.beneficiarioNombre,c.concepto,c.estado,c.monto].map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(','))];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));a.download='reporte-cheques.csv';a.click();URL.revokeObjectURL(a.href);}}
@Component({selector:'app-not-found',standalone:false,template:`<div class="card-panel" style="text-align:center"><h2 class="card-title">404 — Página no encontrada</h2><p>La página solicitada no existe.</p><a class="btn btn-primary" routerLink="/dashboard">Volver al dashboard</a></div>`}) export class NotFoundComponent {}
@Component({selector:'app-usuarios',standalone:false,template:`<div class="card-panel" *ngIf="permitido;else sinPermiso"><div class="card-title-group"><h2 class="card-title">Gestión de usuarios</h2></div><form [formGroup]="form" (ngSubmit)="guardar()" class="form-grid"><div class="form-field"><input class="form-input" formControlName="nombreUsuario" placeholder="Usuario"></div><div class="form-field"><input class="form-input" formControlName="nombreCompleto" placeholder="Nombre completo"></div><div class="form-field"><input class="form-input" formControlName="correo" placeholder="Correo"></div><div class="form-field"><input type="password" class="form-input" formControlName="password" placeholder="Contraseña"></div><div class="form-field"><select class="form-select-native" formControlName="rol"><option>Administrador</option><option>Operador</option><option>Consulta</option></select></div><button class="btn btn-primary">{{editando?'Actualizar':'Crear usuario'}}</button></form><div class="table-responsive" style="margin-top:1rem"><table class="custom-table"><thead><tr><th>Usuario</th><th>Nombre</th><th>Correo</th><th>Rol</th><th>Estado</th><th></th></tr></thead><tbody><tr *ngFor="let u of usuarios"><td>{{u.nombreUsuario}}</td><td>{{u.nombreCompleto}}</td><td>{{u.correo}}</td><td>{{u.rol}}</td><td>{{u.estado}}</td><td><button class="icon-btn edit" (click)="editar(u)"><i class="material-icons">edit</i></button><button class="icon-btn delete" (click)="eliminar(u)"><i class="material-icons">delete</i></button></td></tr></tbody></table></div></div><ng-template #sinPermiso><div class="card-panel"><h2 class="card-title">Acceso restringido</h2><p>Esta pantalla requiere un usuario Administrador.</p></div></ng-template>`})
export class UsuariosComponent implements OnInit {usuarios:Usuario[]=[];permitido=false;editando=false;form;constructor(private fb:FormBuilder,private users:UsuarioService,private session:SessionService,private note:NotificationService){this.form=fb.group({id:[null as number|null],nombreUsuario:['',Validators.required],nombreCompleto:['',Validators.required],correo:['',[Validators.required,Validators.email]],rol:['Operador'],estado:['Activo'],password:['']});}async ngOnInit(){this.permitido=this.session.esAdministrador; if(this.permitido) await this.cargar();}async cargar(){this.usuarios=await this.users.getAll();}editar(u:Usuario){this.editando=true;this.form.patchValue({id:u.id!,nombreUsuario:u.nombreUsuario,nombreCompleto:u.nombreCompleto,correo:u.correo,rol:u.rol,estado:u.estado,password:''});}async guardar(){if(this.form.invalid)return;try{const v:any=this.form.value;if(this.editando)await this.users.update(v,v.password||undefined);else {if(!v.password)throw new Error('La contraseña es requerida.');await this.users.create(v,v.password);}this.note.success('Usuario guardado con éxito.');this.form.reset({rol:'Operador',estado:'Activo',password:''});this.editando=false;await this.cargar();}catch(e:any){this.note.error(e.message||'No se pudo guardar el usuario.');}}async eliminar(u:Usuario){try{await this.users.delete(u.id!);await this.cargar();}catch(e:any){this.note.error(e.message||'No se pudo eliminar.');}}}
