import { Component, OnInit, Directive } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { Banco, Concepto } from '../../models';
import { BancoService } from '../../services/banco.service';
import { ConceptoService } from '../../services/concepto.service';
import { NotificationService } from '../../services/notification.service';
import { LoadingService } from '../../services/loading.service';
import { CatalogoModal } from '../../components/catalogo-modal';
import { ConfirmDialogComponent } from '../../components/confirm-dialog';
@Directive()
abstract class BaseCatalogo implements OnInit { elementos:(Banco|Concepto)[]=[]; filtrados:(Banco|Concepto)[]=[]; texto=''; estado='Todos'; abstract tipo:string; constructor(protected service:any,protected dialog:MatDialog,protected notice:NotificationService,protected loading:LoadingService){} codigo(v:Banco|Concepto):string{return (v as Banco).codigo||'';} async ngOnInit(){await this.cargar();} async cargar(){try{this.elementos=await this.service.getAll();this.filtrar();}catch{this.notice.error('Error al cargar el catálogo.');}} filtrar(){const q=this.texto.toLowerCase();this.filtrados=this.elementos.filter(x=>(x.nombre.toLowerCase().includes(q)||((x as Banco).codigo||'').toLowerCase().includes(q))&&(this.estado==='Todos'||x.estado===this.estado));} abrir(v?:Banco|Concepto){this.dialog.open(CatalogoModal,{width:'480px',data:{tipo:this.tipo,valor:v},disableClose:true}).afterClosed().subscribe(async ok=>{if(ok)await this.cargar();});} borrar(v:Banco|Concepto){this.dialog.open(ConfirmDialogComponent,{width:'400px',data:{title:`¿Eliminar ${this.tipo}?`,message:`¿Desea eliminar ${v.nombre}?`}}).afterClosed().subscribe(async ok=>{if(!ok)return;this.loading.show();try{await this.service.delete(v.id);this.notice.success('Registro eliminado con éxito.');await this.cargar();}catch(e:any){this.notice.error(e.message||'No se pudo eliminar.');}finally{this.loading.hide();}});}}
const template=`<div><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:2rem"><div class="card-title-group" style="margin-bottom:0"><h2 class="card-title">{{tipo}}s</h2><p class="card-subtitle">Administración del catálogo de {{tipo.toLowerCase()}}s</p></div><button class="btn btn-primary" (click)="abrir()"><i class="material-icons">add_circle</i>Agregar</button></div><div class="card-panel"><div class="controls-row"><div class="search-wrapper"><i class="material-icons">search</i><input class="search-input" [(ngModel)]="texto" (ngModelChange)="filtrar()" placeholder="Buscar por nombre o código"></div><div class="filters-wrapper"><select class="filter-select" [(ngModel)]="estado" (change)="filtrar()"><option>Todos</option><option>Activo</option><option>Inactivo</option></select></div></div><div class="table-responsive" *ngIf="filtrados.length;else vacio"><table class="custom-table"><thead><tr><th>Nombre</th><th *ngIf="tipo==='Banco'">Código</th><th>Estado</th><th style="text-align:right">Acciones</th></tr></thead><tbody><tr *ngFor="let v of filtrados"><td>{{v.nombre}}</td><td *ngIf="tipo==='Banco'">{{codigo(v) || '—'}}</td><td><span class="badge" [class.activo]="v.estado==='Activo'" [class.inactivo]="v.estado==='Inactivo'">{{v.estado}}</span></td><td style="text-align:right"><button class="icon-btn edit" (click)="abrir(v)"><i class="material-icons">edit</i></button><button class="icon-btn delete" (click)="borrar(v)"><i class="material-icons">delete</i></button></td></tr></tbody></table></div><ng-template #vacio><div class="no-records"><p>No hay registros para mostrar.</p></div></ng-template></div></div>`;
@Component({selector:'app-bancos',template,standalone:false}) export class BancosComponent extends BaseCatalogo{tipo='Banco';constructor(s:BancoService,d:MatDialog,n:NotificationService,l:LoadingService){super(s,d,n,l);}}
@Component({selector:'app-conceptos',template,standalone:false}) export class ConceptosComponent extends BaseCatalogo{tipo='Concepto';constructor(s:ConceptoService,d:MatDialog,n:NotificationService,l:LoadingService){super(s,d,n,l);}}
